ISSUE10_BUGS = [
    "BUG_HEADING_DYNAMICS_ANOMALY",
    "BUG_TRANSITION_TELEPORT",
    "BUG_MOVEMENT_LOCK_ZONE",
    "BUG_COLLISION_IMPULSE_GLITCH",
    "BUG_CONTEXTUAL_SEQUENCE_FAILURE",
    "BUG_CONTEXTUAL_INTERACTION_OMISSION",
    "BUG_WORLD_STATE_MUTATION",
    "BUG_VIEW_DEPENDENT_MOVEMENT_LOCK",
    "BUG_SLOT_SELECTION_DESYNC",
    "BUG_BREAK_EVENT_CORRUPTION",
]

BUG_JSON_PATH = "envs/bug_definitions_issue10_consistent.json"
